server:
  port: 8080
  error:
    path: /error
fdfs:
  so-timeout: 1500  #获取文件超时时间
  connect-timeout: 600  #连接超时时间
  thumb-image: #生成缩略图
    height: 150
    width: 150
  tracker-list: 192.168.199.138:22122  #tracker配置，多个使用逗号隔开
#  web-server-url: http://192.168.199.138
#  ..其他配置信息..
#  pool:
#    #从池中借出的对象的最大数目（配置为-1表示不限制）
#    max-total: -1
#    #获取连接时的最大等待毫秒数(默认配置为5秒)
#    max-wait-millis: 5000
#    #每个key最大连接数
#    max-total-per-key: 50
#    #每个key对应的连接池最大空闲连接数
#    max-idle-per-key: 10
#    #每个key对应的连接池最小空闲连接数
#    max_idle_per_key: 5