server:
  port: 8080
  error:
    path: /error
fdfs:
  so-timeout: 1500  #获取文件超时时间
  connect-timeout: 600  #连接超时时间
  thumb-image: #生成缩略图
    height: 150
    width: 150
  tracker-list: 192.168.199.138:22122  #tracker配置，多个使用逗号隔开
#  web-server-url: http://192.168.199.138
#  ..其他配置信息..
#  pool:
#    #从池中借出的对象的最大数目（配置为-1表示不限制）
#    max-total: -1
#    #获取连接时的最大等待毫秒数(默认配置为5秒)
#    max-wait-millis: 5000
#    #每个key最大连接数
#    max-total-per-key: 50
#    #每个key对应的连接池最大空闲连接数
#    max-idle-per-key: 10
#    #每个key对应的连接池最小空闲连接数
#    max_idle_per_key: 5

# spring redis cluster 配置
spring:
  redis:
    timeout: 10000
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 172.16.94.206:6379
        - 172.16.94.206:6380
        - 172.16.94.206:6381
        - 172.16.94.206:6382
        - 172.16.94.206:6383
        - 172.16.94.206:6384
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 3 # 连接池中的最小空闲连接
        max-wait: 3 # 连接池最大阻塞等待时间（使用负值表示没有限制）

